version: "3.4"
services:
  vite_docker:
    image: node:alpine
    container_name: vite_docker
    command: yarn dev # เพิ่มคำสั่งนี้เพื่อรัน yarn dev อัตโนมัติ
    ports:
      - 5555:8000
    working_dir: /srv/app
    volumes:
      - type: bind
        source: ./
        target: /srv/app
    tty: true
#https://dev.to/ysmnikhil/how-to-build-with-react-or-vue-with-vite-and-docker-1a3l 